#!/bin/sh
# script for call the favorable depth routine genrealdepth.pl

# Author: Chen Weiwen
# Current Version: 2014/10/10
# Contact jiazhe@mail.ustc.edu.cn vincentc@mail.ustc.edu.cn for more info

# Input: inversion result files *.out generated by CAPjoint code
# Output: the optimal depth result under quadratic fit

cat  $1/data/*_*.out |grep ERR |awk '{gsub($2,""); print $0 }'|awk '{gsub("_"," ");print $4,$12*1e5}' | sort -n > yyy.dat
s=`perl ${CAPCMDHOME}/genrealdepth.pl`
echo $s;
